### ISSUE TITLE
Make jumps a little easier in van gogh

### ISSUE THREAD

**Issue by theoschweizer** [Moonbear2001/Museum-of-Immersive-Art#42]
make sure that you don't have to be hitting any of the jumps in the level at max height/distance.

you shouldn't have to try hard to get to any of the jumps. the level should be about appreciating the art, not about making sure you can do parkour.

This is generally only applicable to the houses, the stars are kinda hard and its ok to keep them that way, but they shouldn't be too hard so also go through this one and make sure that none of them are too hard.

**Comment by Moonbear2001** [comment]
Played through the Van Gogh 1, I think making the jumps any easier reduces playability.
